Change memory requests to standard units
bmuschko/ckad-crash-course pull request #7
Opened 2021-01-06 21:06 UTC by tivanacc

Hi Benjamin,

Thanks a lot for these great exercises and for you course at O'Reilly!

I've noticed that you used `m` as unit for memory (request and quota). You talked about `m` as megabyte.
I've experimented a little bit with it and it turns out that `m` is actually not the same as `M` (megabyte).
```
Error from server (Forbidden): error when creating "pod.yaml": pods "mypod" is forbidden: exceeded quota: app, requested: requests.memory=300M, used: requests.memory=0, limited: requests.memory=500m
```
It looks like - as usual with Kubernetes -, units are case sensitive too.
Valid memory units: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory
Note: I'm not sure what `m` stands for, actually it's even a bit strange that works at all.. :)

In addition, in my proposal I've used both `M` and `Mi`, to make people aware of the difference between the megabyte and mebibyte units.

Hope you find it helpful!
Cheers!
Tamas

2022-02-20 09:52 UTC, dovidio commented
+1 for switching to Mi, I also went through the same problem

m for memory stands for millibyte, that is, a 1/1000th of a byte. From the [Kubernetes documentation](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory):
```
Take care about case for suffixes. If you request 400m of memory, this is a request for 0.4 bytes. Someone who types that probably meant to ask for 400 mebibytes (400Mi) or 400 megabytes (400M).
```

2022-04-13 17:40 UTC, bmuschko requested changes

2022-04-13 17:40 UTC, bmuschko commented on exercises/05-defining-resource-requirements/solution/solution.md
> +Lower the memory settings to less than `500Mi` (e.g. `524M`) and create the Pod.
Wouldn't it be better to use `Mi` here to stay within the same metric? `M` would work but I think it might throw people off? WDYT?

2022-04-14 09:08 UTC, merged

2022-04-14 09:08 UTC, bmuschko commented
Thanks for the changes!